module.exports = {
    data:{
        menus:[
        {
            "name":"购物车",
            "url":'../../images/menu/ic_nav_home_cart.png'
        },
        {
            "name":"分类",
            "url":'../../images/menu/ic_nav_home_category.png'
        },
        {
            "name":"足迹",
            "url":'../../images/menu/ic_nav_home_footprint.png'
        },
        {
            "name":"我的",
            "url":'../../images/menu/ic_nav_home_mine.png'
        },
        {
            "name":"修改",
            "url":'../../images/menu/ic_nav_home_notify.png'
        },
        {
            "name":"预定",
            "url":'../../images/menu/ic_nav_home_order.png'
        },
        {
            "name":"资产",
            "url":'../../images/menu/ic_nav_home_property.png'
        },
        {
            "name":"商铺",
            "url":'../../images/menu/ic_nav_home_store.png'
        },
        ],
  },
} 